import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("dashboard", "routes/dashboard.tsx"),
  route("healthz", "routes/healthz.ts"),
  route("api/auth/*", "routes/api.auth.ts"),
  route("register", "routes/register.tsx"),
  route("login", "routes/login.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("reset-password/:token", "routes/reset-password.$token.tsx"),
  route("legal/terms", "routes/legal.terms.tsx"),
  route("legal/privacy", "routes/legal.privacy.tsx"),
  route("onboarding", "routes/onboarding.tsx"),
  route("academic-terms", "routes/academic-terms._index.tsx"),
  route("academic-terms/:termId", "routes/academic-terms.$termId.tsx"),
  route("activities", "routes/activities._index.tsx"),
  route("activities/new", "routes/activities.new.tsx"),
  route("activities/:activityId", "routes/activities.$activityId.tsx"),
  route("activities/:activityId/edit", "routes/activities.$activityId.edit.tsx"),
  route("courses/:courseId", "routes/courses.$courseId.tsx"),
  route("notes", "routes/notes._index.tsx"),
  route("notes/new", "routes/notes.new.tsx"),
  route("notes/:noteId", "routes/notes.$noteId.tsx"),
  route("files/:attachmentId", "routes/files.$attachmentId.tsx"),
  route("calendar", "routes/calendar.tsx"),
  route("settings/reminders", "routes/settings.reminders.tsx"),
] satisfies RouteConfig;
